### ISSUE TITLE
The Pre-compiled modules for the following Ubuntu kernel Link return 404

### ISSUE THREAD

**Issue by Mundi-Xu** [nyx-fuzz/KVM-Nyx#1]
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.10.73/amd64/linux-image-unsigned-5.10.73-051073-generic_5.10.73-051073.202110131013_amd64.deb

and all the links in the releases.

**Comment by schumilo** [comment]
Thanks for pointing that out! Indeed, the ubuntu kernel release seems to be offline. I just uploaded a new github release which works perfectly fine with kernel 5.10.75.

https://github.com/nyx-fuzz/KVM-Nyx/releases/tag/v5.10.73-1.1

Could you please give it a try and let me know if this release works for you?
