### ISSUE TITLE
Usermode tests does not output Intel PT data stream

### ISSUE THREAD

**Issue by jkrshnmenon** [nyx-fuzz/KVM-Nyx#6]
I am using KVM-Nyx on a processor that supports Intel PT.
I've installed the kernel according to the installation instructions provided here : https://intellabs.github.io/kAFL/tutorials/installation.html
And I have verified that the kafl kernel is being used

```
$ uname -a
Linux jay 5.10.73-kafl+ #1 SMP Fri Mar 18 13:20:22 CET 2022 x86_64 x86_64 x86_64 GNU/Linux
```

However, when I try to run the tests under `usermode-test/`, I do not see any output of the Intel PT data stream.
I compiled the tests using `usermode-test/compile.sh` and upon running `test-verbose`, the output is as follows

```
$ ./test_verbose

KVM-PT: CPU supports 2 IP filters!
KVM_VMX_PT_GET_TOPA_SIZE: 0x410000
KVM_EXIT_IO
KVM_EXIT_IO
KVM_EXIT_IO
KVM_EXIT_IO
KVM_EXIT_HLT (Final ToPA dump)
$
```

I was wondering if this was the intended result or if Intel PT is supposed to be generating some output here ?
Please advise.

**Comment by schumilo** [comment]
Hi there!
The usermode-test code is for debugging and development purposes only. So yes, that is absolutely the expected output for this specific program. Running `test-verbose-loop` for instance, will get you the output of the trace buffer once that one is full. 

But If you are looking for a more complete userland implementation for kvm-nyx, check out [QEMU-Nyx](https://github.com/nyx-fuzz/QEMU-Nyx) or [KVM-Fuzz](https://github.com/klecko/kvm-fuzz).

**Comment by jkrshnmenon** [comment]
That explains a lot. Thank you for that.
I will look into those repositories.
Thank you!

I'll mark this issue as closed as well.
